apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ddp

resources:
  - namespace.yaml
  - istio-ingress-gateway.yaml
  - repository.yaml
  - release.yaml

secretGenerator:
- name: env-config
  files:
    - env/.env
  type: Opaque

# configurations:
#   - kustomizeconfig.yaml