apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ddp
  namespace: ddp
spec:
  interval: 1m
  valuesFrom:
      - kind: Secret
        name: env-config-49gchcccd7
  chart:
    spec:
      chart: ./chart
      version: '*'
      sourceRef:
        kind: GitRepository
        name: ddp
        namespace: flux-system
      interval: 1m
      