apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./mongo.deployment.yaml
- ./mongo.svc.yaml
- ./mongo.pv.yaml
- ./mongo.pvc.yaml

images:
- name: mongo
  newName: mongo
  newTag: latest