apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddp-api
  labels:
    app: ddp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddp-api
  template:
    metadata:
      labels:
        app: ddp-api
    spec:
      containers:
      - name: ddp-api
        image: localhost:5500/ddp-api:latest
        ports:
        - containerPort: 8900