apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name}}-mongo-pvc
  namespace: {{ .Values.namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""