apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddp-mongo
  template:
    metadata:
      labels:
        app: ddp-mongo
    spec:
      containers:
      - name: ddp-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-pvc
          mountPath: /data
      
      volumes:
      - name: mongo-pvc
        persistentVolumeClaim:
          claimName: {{ .Release.Name}}-mongo-pvc