apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-api-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - protocol: TCP
      port: 8900
      targetPort: 8900
      nodePort: 30000